#!/bin/bash

dn=src/autogen

create_file() {
	fn=$dn/$3.c
	echo "// automatically generated by gen_memory_files.sh" > "$fn"
	echo "#include <ws.h>" >> "$fn"
	echo '__attribute__((section(".'$1'.'$3'")))' >> "$fn"
	echo $2" ws_iram "$3";" >> "$fn"
}

mkdir -p $dn
rm $dn/*
for i in $(seq 1 8); do
	create_file iramx_screen ws_screen_t wse_screen"$i"
	create_file iramx_sprite ws_sprite_table_t wse_sprites"$i"
	create_file iramx_wave ws_sound_wavetable_t wse_wavetable"$i"
done
